### ISSUE TITLE
Windows: connection failed error

### ISSUE THREAD

**Issue by Moabbit** [PierreRochard/node-launcher#58]
when I click unlock wallet, or create wallet it gives me this error

![download_20181216_121348](https://user-images.githubusercontent.com/40186550/50057755-3a4fae00-012c-11e9-9d65-3bab230adb25.png)

![download_20181216_121355](https://user-images.githubusercontent.com/40186550/50057763-5ce1c700-012c-11e9-9ce1-000ef0d442f1.jpg)

![download_20181216_121450](https://user-images.githubusercontent.com/40186550/50057766-63703e80-012c-11e9-9739-2d9cf43fb340.jpg)

**Comment by Freefromchainz** [comment]
same thing here for me aswell!
![connection failed 2](https://user-images.githubusercontent.com/8317700/50161374-dd253b00-0298-11e9-81ea-3dfb374c1c66.PNG)

**Comment by PierreRochard** [comment]
Hi @Freefromchainz and  @Moabbit I just pushed a new release which I think will fix this, please try it out!

**Comment by Freefromchainz** [comment]
ok just tried it out still getting this at faster rate the error message just keeps replicating E1218 10:32:18.559000000  4804 src/core/tsi/ssl_transport_security.cc:1229] Handshake failed with fatal error SSL_ERROR_SSL: error:10000410:SSL routines:OPENSSL_internal:SSLV3_ALERT_HANDSHAKE_FAILURE.

however when i open the launcher i notice lnd was greyed until bitcoin was active!

**Comment by PierreRochard** [comment]
Yes, Bitcoin has to be active for LND to be launched, that was the case before but I made this explicit with the buttons

The unlock/create/recover buttons will be greyed out until you launch LND

**Comment by Freefromchainz** [comment]
Yes indeed I was letting you know that, that part of functionality was working but the ssl error is the problem now. after launching lnd it keeps going and the buttons remain greyed because lnd is not connecting most likely due to the tsi ssl transport error

**Comment by PierreRochard** [comment]
Ah ok, thanks. Does rebooting and restarting everything help?

**Comment by Freefromchainz** [comment]
still the same SSL handshake error! after rebooting three times
![connection failed 3](https://user-images.githubusercontent.com/8317700/50178884-e1664e00-02c2-11e9-906d-fbf22b9339b6.PNG)

**Comment by PierreRochard** [comment]
Ok, I'll look into it, what Operating System are you using?

**Comment by PierreRochard** [comment]
Also, is this your first time running LND or did you run it before the Node Launcher?

**Comment by PierreRochard** [comment]
Try going to %localappdata%/Lnd and deleting the tls.cert and tls.key files there

**Comment by Freefromchainz** [comment]
deleting those two files worked! thanks alot for the quick responses!
